//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.27 at 11:37:11 AM GMT-10:00 
//


package org.hackystat.sensorbase.resource.projects.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ProjectSummary" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}LastMod"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectSummary"
})
@XmlRootElement(name = "MultiDayProjectSummary")
public class MultiDayProjectSummary
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "ProjectSummary", required = true)
    protected List<ProjectSummary> projectSummary;
    @XmlAttribute(name = "LastMod")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastMod;

    /**
     * Gets the value of the projectSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProjectSummary }
     * 
     * 
     */
    public List<ProjectSummary> getProjectSummary() {
        if (projectSummary == null) {
            projectSummary = new ArrayList<ProjectSummary>();
        }
        return this.projectSummary;
    }

    public boolean isSetProjectSummary() {
        return ((this.projectSummary!= null)&&(!this.projectSummary.isEmpty()));
    }

    public void unsetProjectSummary() {
        this.projectSummary = null;
    }

    /**
     * Gets the value of the lastMod property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastMod() {
        return lastMod;
    }

    /**
     * Sets the value of the lastMod property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastMod(XMLGregorianCalendar value) {
        this.lastMod = value;
    }

    public boolean isSetLastMod() {
        return (this.lastMod!= null);
    }

}
