//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.05 at 11:08:45 AM GMT-10:00 
//


package org.hackystat.sensorbase.resource.projects.jaxb;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{}SensorDataType use="required""/>
 *       &lt;attribute ref="{}Tool use="required""/>
 *       &lt;attribute ref="{}NumInstances use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "SensorDataSummary")
public class SensorDataSummary
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlAttribute(name = "SensorDataType", required = true)
    protected String sensorDataType;
    @XmlAttribute(name = "Tool", required = true)
    protected String tool;
    @XmlAttribute(name = "NumInstances", required = true)
    protected BigInteger numInstances;

    /**
     * Gets the value of the sensorDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorDataType() {
        return sensorDataType;
    }

    /**
     * Sets the value of the sensorDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorDataType(String value) {
        this.sensorDataType = value;
    }

    public boolean isSetSensorDataType() {
        return (this.sensorDataType!= null);
    }

    /**
     * Gets the value of the tool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTool() {
        return tool;
    }

    /**
     * Sets the value of the tool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTool(String value) {
        this.tool = value;
    }

    public boolean isSetTool() {
        return (this.tool!= null);
    }

    /**
     * Gets the value of the numInstances property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumInstances() {
        return numInstances;
    }

    /**
     * Sets the value of the numInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumInstances(BigInteger value) {
        this.numInstances = value;
    }

    public boolean isSetNumInstances() {
        return (this.numInstances!= null);
    }

}
