//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.19 at 12:42:32 PM GMT-10:00 
//


package org.hackystat.sensorbase.resource.projects.jaxb;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SensorDataSummary" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}NumInstances use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sensorDataSummary"
})
@XmlRootElement(name = "SensorDataSummaries")
public class SensorDataSummaries
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "SensorDataSummary")
    protected List<SensorDataSummary> sensorDataSummary;
    @XmlAttribute(name = "NumInstances", required = true)
    protected BigInteger numInstances;

    /**
     * Gets the value of the sensorDataSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorDataSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorDataSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorDataSummary }
     * 
     * 
     */
    public List<SensorDataSummary> getSensorDataSummary() {
        if (sensorDataSummary == null) {
            sensorDataSummary = new ArrayList<SensorDataSummary>();
        }
        return this.sensorDataSummary;
    }

    public boolean isSetSensorDataSummary() {
        return ((this.sensorDataSummary!= null)&&(!this.sensorDataSummary.isEmpty()));
    }

    public void unsetSensorDataSummary() {
        this.sensorDataSummary = null;
    }

    /**
     * Gets the value of the numInstances property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumInstances() {
        return numInstances;
    }

    /**
     * Sets the value of the numInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumInstances(BigInteger value) {
        this.numInstances = value;
    }

    public boolean isSetNumInstances() {
        return (this.numInstances!= null);
    }

}
