//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.25 at 11:27:48 PM CST 
//


package org.hackystat.sensorbase.resource.dpd.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hackystat.sensorbase.resource.dpd.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hackystat.sensorbase.resource.dpd.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MemberData }
     * 
     */
    public MemberData createMemberData() {
        return new MemberData();
    }

    /**
     * Create an instance of {@link UnitTestDailyProjectData }
     * 
     */
    public UnitTestDailyProjectData createUnitTestDailyProjectData() {
        return new UnitTestDailyProjectData();
    }

}
